/**
 * Tansik 2026, phase 1 — minimum scores announced by the Minister of Higher Education on 2026-08-10
 * (out of 320, "modern system" secondary certificate). Only the faculties named in the
 * announcement; later phases and other faculties are not covered.
 * Source (raw Arabic text kept in research notes): https://www.youm7.com/story/2026/8/10/-/7509371
 *
 * [university slug, faculty name as stored (or kind for the standard name), track, score]
 */
export const CUTOFFS_2026_SOURCE = 'https://www.youm7.com/story/2026/8/10/-/7509371';

export type Track = 'science_bio' | 'science_math' | 'literary';
type Row = readonly [university: string, faculty: string, track: Track, score: number];

const bio = (u: string, f: string, s: number): Row => [u, f, 'science_bio', s];
const math = (u: string, f: string, s: number): Row => [u, f, 'science_math', s];
const lit = (u: string, f: string, s: number): Row => [u, f, 'literary', s];

export const CUTOFFS_2026: Row[] = [
  // medicine
  bio('mansoura', 'med', 309),
  bio('alexandria', 'med', 308.5),
  bio('cairo', 'med', 308),
  bio('zagazig', 'med', 308),
  bio('damietta', 'med', 307.5),
  bio('tanta', 'med', 307),
  bio('kafrelsheikh', 'med', 306.5),
  bio('benha', 'med', 306),
  bio('ain-shams', 'med', 305.5),
  bio('port-said', 'med', 305),
  bio('menoufia', 'med', 305),
  bio('capital', 'med', 304.5),
  bio('suez-canal', 'med', 304.5),
  bio('sadat-city', 'med', 304.5),
  bio('suez', 'med', 304),
  bio('fayoum', 'med', 304),
  bio('beni-suef', 'med', 303.5),
  bio('minia', 'med', 303),
  bio('sohag', 'med', 303),
  bio('arish', 'med', 303),
  bio('assiut', 'med', 302.5),
  bio('qena', 'med', 302),
  bio('luxor', 'med', 301.5),
  bio('new-valley', 'med', 301.5),
  bio('aswan', 'med', 301),
  // dentistry
  bio('mansoura', 'dent', 300.5),
  bio('kafrelsheikh', 'dent', 300),
  bio('zagazig', 'dent', 300),
  bio('tanta', 'dent', 300),
  bio('alexandria', 'dent', 300),
  bio('cairo', 'dent', 300),
  bio('ain-shams', 'dent', 299.5),
  bio('suez-canal', 'dent', 299.5),
  bio('sohag', 'dent', 299.5),
  bio('menoufia', 'dent', 299.5),
  bio('suez', 'dent', 299),
  bio('fayoum', 'dent', 299),
  bio('qena', 'dent', 299),
  bio('beni-suef', 'dent', 298.7),
  bio('assiut', 'dent', 298.5),
  bio('minia', 'dent', 298.5),
  // pharmacy & physical therapy
  bio('mansoura', 'pharm', 298),
  bio('sohag', 'pharm', 297.5),
  bio('kafrelsheikh', 'pt', 297.5),
  bio('port-said', 'pt', 297),
  bio('benha', 'pt', 297),
  bio('tanta', 'pharm', 297),
  bio('zagazig', 'pharm', 297),
  bio('suez-canal', 'pharm', 297),
  bio('qena', 'pharm', 296.5),
  bio('menoufia', 'pharm', 296.5),
  bio('cairo', 'pharm', 296.5),
  bio('damanhour', 'pharm', 296.5),
  bio('cairo', 'pt', 296.5),
  bio('kafrelsheikh', 'pharm', 296.5),
  bio('suez-canal', 'pt', 296.5),
  bio('qena', 'pt', 296),
  bio('alexandria', 'pharm', 296),
  bio('port-said', 'pharm', 296),
  bio('ain-shams', 'pharm', 296),
  bio('assiut', 'pharm', 296),
  bio('suez', 'pt', 296),
  bio('sohag', 'cs', 292.5),
  // engineering (math track)
  math('suez', 'eng-petroleum', 302),
  math('menoufia', 'كلية الهندسة الإلكترونية بمنوف', 291),
  math('mansoura', 'eng', 290.5),
  math('suez-canal', 'eng', 290),
  math('cairo', 'eng', 289.5),
  math('ain-shams', 'eng', 288.5),
  math('damietta', 'eng', 287.5),
  math('zagazig', 'eng', 286.5),
  math('port-said', 'eng', 285),
  math('tanta', 'eng', 285),
  math('alexandria', 'eng', 284.5),
  math('kafrelsheikh', 'eng', 284),
  math('benha', 'كلية الهندسة بشبرا', 284),
  math('damanhour', 'eng', 283.5),
  math('benha', 'كلية الهندسة ببنها', 283),
  math('menoufia', 'كلية الهندسة بشبين الكوم', 282.5),
  math('capital', 'كلية الهندسة بحلوان', 282.5),
  math('suez', 'eng', 282.2),
  math('capital', 'كلية الهندسة بالمطرية', 281.5),
  math('fayoum', 'eng', 280.5),
  math('beni-suef', 'eng', 279.5),
  math('minia', 'eng', 278.5),
  math('aswan', 'eng', 278),
  math('qena', 'eng', 278),
  math('sohag', 'eng', 277.5),
  math('assiut', 'eng', 277.5),
  math('new-valley', 'eng', 277),
  math('aswan', 'eng-energy', 276.5),
  // literary
  lit('cairo', 'econ-pol', 299),
  lit('kafrelsheikh', 'alsun', 299),
  lit('alexandria', 'كلية الدراسات الاقتصادية والعلوم السياسية', 294),
  lit('ain-shams', 'alsun', 292),
  lit('cairo', 'media', 289),
  lit('suez-canal', 'alsun', 288.5),
  lit('suez', 'كلية السياسة والاقتصاد', 288.5),
  lit('fayoum', 'alsun', 288),
  lit('ain-shams', 'media', 286),
  lit('beni-suef', 'كلية الدراسات الاقتصادية والعلوم السياسية', 286),
  lit('hurghada', 'alsun', 285),
  lit('beni-suef', 'alsun', 284),
  lit('menoufia', 'media', 282),
  lit('minia', 'alsun', 282),
  lit('sohag', 'alsun', 280.5),
  lit('zagazig', 'disability', 279),
  lit('luxor', 'alsun', 279),
  lit('aswan', 'alsun', 278.5),
  lit('suez', 'كلية الإعلام وتكنولوجيا الاتصال', 278),
  lit('beni-suef', 'media', 277.5),
  lit('qena', 'كلية الإعلام وتكنولوجيا الاتصال', 275.5),
  lit('cairo', 'archaeology', 273),
  lit('ain-shams', 'archaeology', 272),
  lit('zagazig', 'archaeology', 271.5),
  lit('damietta', 'archaeology', 270.5),
  lit('fayoum', 'archaeology', 268.5),
  lit('matrouh', 'كلية الآثار واللغات', 264.5),
  lit('aswan', 'archaeology', 264.5),
  lit('luxor', 'archaeology', 262.5),
  lit('sohag', 'archaeology', 259),
  lit('qena', 'archaeology', 257),
  lit('port-said', 'law', 271.5),
  lit('qena', 'law', 260.5),
  lit('sohag', 'law', 259),
  lit('kafrelsheikh', 'law', 243.5),
  lit('aswan', 'law', 243),
  lit('minia', 'law', 242),
  lit('damietta', 'law', 239.5),
  lit('fayoum', 'law', 238.5),
  lit('cairo', 'arts', 259.5),
  lit('ain-shams', 'arts', 252),
  lit('alexandria', 'arts', 248.5),
  lit('capital', 'arts', 246),
  lit('benha', 'arts', 241),
  lit('damanhour', 'arts', 230.5),
  lit('menoufia', 'arts', 230),
  lit('fayoum', 'arts', 229),
  lit('cairo', 'com', 253),
  lit('alexandria', 'كلية الأعمال', 251),
  lit('ain-shams', 'com', 250.5),
  lit('damietta', 'com', 248),
  lit('qena', 'com', 244.5),
  lit('zagazig', 'com', 241.5),
  lit('benha', 'com', 241.5),
  lit('damanhour', 'com', 241),
  lit('mansoura', 'com', 237.5),
  lit('menoufia', 'com', 237),
  lit('aswan', 'com', 235.5),
  lit('beni-suef', 'com', 233.5),
  lit('tanta', 'com', 233.5),
  lit('suez-canal', 'com', 231),
  lit('kafrelsheikh', 'com', 231),
  lit('assiut', 'com', 230),
  lit('zagazig', 'edu', 258.5),
  lit('alexandria', 'edu', 256),
  lit('ain-shams', 'edu', 254.5),
  lit('port-said', 'edu', 252),
  lit('mansoura', 'edu', 251),
  lit('benha', 'edu', 248.5),
  lit('damanhour', 'edu', 248),
  lit('tanta', 'edu', 247.5),
  lit('menoufia', 'edu', 242.5),
  lit('suez-canal', 'edu', 242),
  lit('kafrelsheikh', 'edu', 242),
  lit('minia', 'edu', 241.5),
  lit('capital', 'edu', 241),
  lit('suez', 'edu', 234.5),
  lit('sadat-city', 'edu', 234),
  lit('fayoum', 'edu', 233.5),
  lit('damietta', 'edu', 232.5),
  lit('hurghada', 'edu', 231.5),
  lit('beni-suef', 'edu', 229),
];
