/**
 * Faculty kinds — "الهندسة" as a field of study, across universities (Phase 11, real data).
 *
 * Texts are general, factual descriptions of each field in Egyptian public universities: study length,
 * how specialisation works, admission tests where they apply. University-specific facts (departments,
 * accreditation, cutoffs) live on each faculty, with their sources. Researched 2026-10-09.
 */
import type { FacultyCategory } from '../../src/generated/prisma/enums.js';

export interface KindSeed {
  slug: string;
  nameAr: string;
  fullNameAr: string;
  icon: string;
  category: FacultyCategory;
  /** Academic years before any internship / training year. */
  studyYears: number;
  summary: string;
  about: string;
  genericInfo: string;
}

export const KINDS: KindSeed[] = [
  // ---------- medical ----------
  {
    slug: 'med',
    nameAr: 'الطب',
    fullNameAr: 'كلية الطب البشري',
    icon: 'pulse',
    category: 'medical',
    studyYears: 5,
    summary: 'طب بشري: علوم أساسية ثم إكلينيكي ثم امتياز',
    about:
      'خمس سنين دراسة بنظام الساعات المعتمدة، وبعدها سنتين امتياز في المستشفيات قبل مزاولة المهنة. السنين الأولى علوم أساسية، والباقي إكلينيكي في المستشفى الجامعي.',
    genericInfo:
      'تمنح الكلية بكالوريوس الطب والجراحة (MBBCh). النظام الحالي خمس سنوات دراسية تليها سنتان تدريب إجباري (امتياز).',
  },
  {
    slug: 'dent',
    nameAr: 'طب الأسنان',
    fullNameAr: 'كلية طب الفم والأسنان',
    icon: 'tooth',
    category: 'medical',
    studyYears: 5,
    summary: 'علوم أساسية، معامل، ثم عيادات',
    about: 'خمس سنين وسنة امتياز. الجزء العملي في المعامل بيبدأ بدري، والعيادات في السنين الأخيرة.',
    genericInfo:
      'تمنح الكلية بكالوريوس طب وجراحة الفم والأسنان، ومدة الدراسة خمس سنوات تليها سنة امتياز.',
  },
  {
    slug: 'pharm',
    nameAr: 'الصيدلة',
    fullNameAr: 'كلية الصيدلة',
    icon: 'pill',
    category: 'medical',
    studyYears: 5,
    summary: 'فارم دي، صيدلة إكلينيكية، تصنيع دوائي',
    about:
      'برنامج فارم دي (Pharm D): خمس سنين دراسة وسنة تدريب عملي. فيه برامج متخصصة زي الصيدلة الإكلينيكية في كليات كتير.',
    genericInfo:
      'تمنح الكلية بكالوريوس الصيدلة (فارم دي)، ويشمل البرنامج سنة تدريب ميداني بعد السنوات الدراسية.',
  },
  {
    slug: 'vet',
    nameAr: 'الطب البيطري',
    fullNameAr: 'كلية الطب البيطري',
    icon: 'pulse',
    category: 'medical',
    studyYears: 5,
    summary: 'صحة الحيوان، الثروة الحيوانية، الرقابة على الغذاء',
    about: 'خمس سنين. بتدرس تشريح وأمراض وعلاج الحيوان، وكمان سلامة الأغذية ذات الأصل الحيواني.',
    genericInfo: 'تمنح الكلية بكالوريوس العلوم الطبية البيطرية، ومدة الدراسة خمس سنوات.',
  },
  {
    slug: 'nursing',
    nameAr: 'التمريض',
    fullNameAr: 'كلية التمريض',
    icon: 'pulse',
    category: 'medical',
    studyYears: 4,
    summary: 'تمريض باطني جراحي، أطفال، نساء، صحة مجتمع',
    about: 'أربع سنين وسنة امتياز في المستشفيات. التدريب العملي جزء أساسي من كل سنة.',
    genericInfo: 'تمنح الكلية بكالوريوس علوم التمريض، ومدة الدراسة أربع سنوات تليها سنة امتياز.',
  },
  {
    slug: 'pt',
    nameAr: 'العلاج الطبيعي',
    fullNameAr: 'كلية العلاج الطبيعي',
    icon: 'people',
    category: 'medical',
    studyYears: 5,
    summary: 'تأهيل العظام والأعصاب والقلب والأطفال',
    about: 'خمس سنين وسنة امتياز. بتدرس العلوم الطبية الأساسية وبعدها تخصصات العلاج والتأهيل.',
    genericInfo: 'تمنح الكلية بكالوريوس العلاج الطبيعي، ومدة الدراسة خمس سنوات تليها سنة امتياز.',
  },
  {
    slug: 'applied-med',
    nameAr: 'العلوم الطبية التطبيقية',
    fullNameAr: 'كلية العلوم الطبية التطبيقية',
    icon: 'pulse',
    category: 'medical',
    studyYears: 4,
    summary: 'معامل طبية، أشعة، تقنيات صحية',
    about: 'برامج في التخصصات الطبية المساعدة زي المختبرات الطبية والأشعة، حسب الجامعة.',
    genericInfo: 'تخرّج الكلية أخصائيين في التقنيات الطبية المساعدة.',
  },
  {
    slug: 'health-sci',
    nameAr: 'العلوم الصحية',
    fullNameAr: 'كلية العلوم الصحية',
    icon: 'pulse',
    category: 'medical',
    studyYears: 4,
    summary: 'تخصصات صحية تطبيقية',
    about: 'برامج تطبيقية في المجالات الصحية، وتفاصيلها بتختلف من جامعة للتانية.',
    genericInfo: 'كلية حديثة تقدم برامج في العلوم الصحية التطبيقية.',
  },
  {
    slug: 'nutrition',
    nameAr: 'علوم التغذية',
    fullNameAr: 'كلية علوم التغذية',
    icon: 'pulse',
    category: 'medical',
    studyYears: 4,
    summary: 'تغذية علاجية، سلامة غذاء',
    about: 'أربع سنين في علوم التغذية والتغذية العلاجية.',
    genericInfo: 'تؤهل الكلية أخصائيي التغذية للعمل في القطاع الصحي والغذائي.',
  },

  // ---------- engineering ----------
  {
    slug: 'eng',
    nameAr: 'الهندسة',
    fullNameAr: 'كلية الهندسة',
    icon: 'gear',
    category: 'engineering',
    studyYears: 5,
    summary: 'مدني، عمارة، كهرباء، ميكانيكا، حاسبات',
    about:
      'خمس سنين: سنة إعدادي مشتركة، وبعدها بتتوزع على الأقسام حسب مجموعك ورغباتك. كليات كتير فيها كمان برامج ساعات معتمدة بمصروفات.',
    genericInfo:
      'تمنح الكلية بكالوريوس الهندسة في تخصصات مثل المدنية والمعمارية والكهربائية والميكانيكية.',
  },
  {
    slug: 'eng-electronic',
    nameAr: 'الهندسة الإلكترونية',
    fullNameAr: 'كلية الهندسة الإلكترونية',
    icon: 'gear',
    category: 'engineering',
    studyYears: 5,
    summary: 'إلكترونيات، اتصالات، حاسبات، تحكم',
    about: 'كلية هندسة متخصصة في الإلكترونيات والاتصالات وهندسة الحاسبات.',
    genericInfo: 'تمنح الكلية بكالوريوس الهندسة الإلكترونية، ومدة الدراسة خمس سنوات.',
  },
  {
    slug: 'eng-petroleum',
    nameAr: 'هندسة البترول والتعدين',
    fullNameAr: 'كلية هندسة البترول والتعدين',
    icon: 'gear',
    category: 'engineering',
    studyYears: 5,
    summary: 'بترول، تعدين، فلزات',
    about: 'كلية هندسة متخصصة في هندسة البترول والتعدين والفلزات.',
    genericInfo: 'تمنح الكلية بكالوريوس الهندسة في البترول والتعدين.',
  },
  {
    slug: 'eng-energy',
    nameAr: 'هندسة الطاقة',
    fullNameAr: 'كلية هندسة الطاقة',
    icon: 'gear',
    category: 'engineering',
    studyYears: 5,
    summary: 'قوى كهربية، طاقة جديدة ومتجددة',
    about: 'كلية هندسة متخصصة في هندسة الطاقة بفروعها.',
    genericInfo: 'تمنح الكلية بكالوريوس هندسة الطاقة.',
  },
  {
    slug: 'planning',
    nameAr: 'التخطيط الإقليمي والعمراني',
    fullNameAr: 'كلية التخطيط الإقليمي والعمراني',
    icon: 'building',
    category: 'engineering',
    studyYears: 5,
    summary: 'تخطيط مدن، تصميم عمراني، تخطيط إقليمي',
    about: 'خمس سنين للشعبة الهندسية، في تخطيط المدن والأقاليم والتصميم العمراني.',
    genericInfo: 'تمنح الكلية بكالوريوس التخطيط العمراني.',
  },
  {
    slug: 'tech-edu',
    nameAr: 'التكنولوجيا والتعليم',
    fullNameAr: 'كلية التكنولوجيا والتعليم',
    icon: 'gear',
    category: 'engineering',
    studyYears: 4,
    summary: 'تكنولوجيا صناعية وإعداد معلم فني',
    about:
      'أربع سنين. بتؤهلك تشتغل في المجالات التكنولوجية والتعليم الفني. اسمها القديم كان «التعليم الصناعي» في جامعات كتير.',
    genericInfo:
      'تمتد الدراسة أربع سنوات وتؤهل الخريجين للعمل في المجالات التكنولوجية والتعليم الفني.',
  },
  {
    slug: 'cs',
    nameAr: 'الحاسبات والمعلومات',
    fullNameAr: 'كلية الحاسبات والمعلومات',
    icon: 'code',
    category: 'engineering',
    studyYears: 4,
    summary: 'علوم حاسب، نظم، ذكاء اصطناعي',
    about:
      'أربع سنين: سنتين عام وبعدهم تخصص، زي علوم الحاسب أو نظم المعلومات أو الذكاء الاصطناعي. كليات كتير اتغير اسمها لـ«الحاسبات والذكاء الاصطناعي».',
    genericInfo:
      'تضم الكلية أقسامًا مثل علوم الحاسب ونظم المعلومات وتكنولوجيا المعلومات، ومدة الدراسة أربع سنوات.',
  },

  // ---------- science ----------
  {
    slug: 'sci',
    nameAr: 'العلوم',
    fullNameAr: 'كلية العلوم',
    icon: 'pulse',
    category: 'science',
    studyYears: 4,
    summary: 'كيمياء، فيزياء، أحياء، جيولوجيا، رياضيات',
    about: 'أربع سنين. فيها شعب لطلاب علمي علوم وشعب لطلاب علمي رياضة، والتخصص حسب البرنامج.',
    genericInfo:
      'تضم الكلية أقسام الكيمياء والفيزياء وعلوم الحياة والجيولوجيا والرياضيات، ومدة الدراسة أربع سنوات.',
  },
  {
    slug: 'agri',
    nameAr: 'الزراعة',
    fullNameAr: 'كلية الزراعة',
    icon: 'globe',
    category: 'science',
    studyYears: 4,
    summary: 'إنتاج نباتي وحيواني، صناعات غذائية، اقتصاد زراعي',
    about:
      'أربع سنين، وبرامج متخصصة كتير زي الصناعات الغذائية والتكنولوجيا الحيوية في بعض الكليات.',
    genericInfo: 'تمنح الكلية بكالوريوس العلوم الزراعية، ومدة الدراسة أربع سنوات.',
  },
  {
    slug: 'fisheries',
    nameAr: 'الثروة السمكية',
    fullNameAr: 'كلية علوم الثروة السمكية',
    icon: 'globe',
    category: 'science',
    studyYears: 4,
    summary: 'استزراع سمكي، مصايد، تكنولوجيا الأسماك',
    about: 'أربع سنين في الاستزراع السمكي والمصايد وتصنيع الأسماك.',
    genericInfo: 'تخرّج الكلية متخصصين في الثروة السمكية والاستزراع المائي.',
  },
  {
    slug: 'earth-sci',
    nameAr: 'علوم الأرض',
    fullNameAr: 'كلية علوم الأرض',
    icon: 'globe',
    category: 'science',
    studyYears: 4,
    summary: 'جيولوجيا، جيوفيزياء، ثروات معدنية',
    about: 'أربع سنين في علوم الأرض وتطبيقاتها في البترول والتعدين والمياه.',
    genericInfo: 'كلية متخصصة في علوم الأرض.',
  },
  {
    slug: 'space-sci',
    nameAr: 'الملاحة وتكنولوجيا الفضاء',
    fullNameAr: 'كلية علوم الملاحة وتكنولوجيا الفضاء',
    icon: 'globe',
    category: 'science',
    studyYears: 4,
    summary: 'علوم الفضاء، الاستشعار عن بعد، الملاحة',
    about: 'كلية متخصصة في علوم الفضاء والملاحة وتطبيقاتها.',
    genericInfo: 'من أحدث الكليات المتخصصة في علوم الفضاء في مصر.',
  },
  {
    slug: 'home-econ',
    nameAr: 'الاقتصاد المنزلي',
    fullNameAr: 'كلية الاقتصاد المنزلي',
    icon: 'people',
    category: 'science',
    studyYears: 4,
    summary: 'تغذية، ملابس ونسيج، إدارة منزل',
    about: 'أربع سنين في التغذية وعلوم الأطعمة والملابس والنسيج وإدارة المنزل.',
    genericInfo: 'تمنح الكلية بكالوريوس الاقتصاد المنزلي.',
  },
  {
    slug: 'sugar-tech',
    nameAr: 'تكنولوجيا صناعة السكر',
    fullNameAr: 'كلية تكنولوجيا صناعة السكر والصناعات التكاملية',
    icon: 'gear',
    category: 'science',
    studyYears: 4,
    summary: 'صناعة السكر والصناعات المرتبطة بيها',
    about: 'كلية متخصصة في تكنولوجيا صناعة السكر والصناعات التكاملية معاها.',
    genericInfo: 'كلية فريدة من نوعها في صناعة السكر.',
  },

  // ---------- literary / humanities ----------
  {
    slug: 'law',
    nameAr: 'الحقوق',
    fullNameAr: 'كلية الحقوق',
    icon: 'scale',
    category: 'literary',
    studyYears: 4,
    summary: 'قانون عام وخاص، شعب لغات',
    about: 'أربع سنين، وكليات كتير فيها شعبة عربي وشعب لغات بالإنجليزي أو الفرنساوي.',
    genericInfo: 'تمنح الكلية ليسانس الحقوق، ومدة الدراسة أربع سنوات.',
  },
  {
    slug: 'com',
    nameAr: 'التجارة',
    fullNameAr: 'كلية التجارة',
    icon: 'chart',
    category: 'literary',
    studyYears: 4,
    summary: 'محاسبة، إدارة أعمال، اقتصاد، شعب لغات',
    about: 'أربع سنين، شعبة عربي أو إنجليزي، والتخصص بيبدأ في السنين الأخيرة.',
    genericInfo:
      'تضم كليات التجارة شعب المحاسبة وإدارة الأعمال والاقتصاد، بالإضافة إلى برامج باللغات.',
  },
  {
    slug: 'econ-pol',
    nameAr: 'الاقتصاد والعلوم السياسية',
    fullNameAr: 'كلية الاقتصاد والعلوم السياسية',
    icon: 'chart',
    category: 'literary',
    studyYears: 4,
    summary: 'اقتصاد، علوم سياسية، إحصاء، إدارة عامة',
    about: 'أربع سنين في الاقتصاد والسياسة والإحصاء، ومن أعلى الكليات الأدبية في التنسيق.',
    genericInfo: 'تضم أقسام الاقتصاد والعلوم السياسية والإحصاء والإدارة العامة.',
  },
  {
    slug: 'media',
    nameAr: 'الإعلام',
    fullNameAr: 'كلية الإعلام',
    icon: 'mic',
    category: 'literary',
    studyYears: 4,
    summary: 'صحافة، إذاعة وتلفزيون، علاقات عامة وإعلان',
    about: 'أربع سنين، والتخصص في الصحافة أو الإذاعة والتلفزيون أو العلاقات العامة والإعلان.',
    genericInfo: 'تؤهل الكلية الطلاب للعمل في الصحافة والإذاعة والتلفزيون والعلاقات العامة.',
  },
  {
    slug: 'arts',
    nameAr: 'الآداب',
    fullNameAr: 'كلية الآداب',
    icon: 'history',
    category: 'literary',
    studyYears: 4,
    summary: 'لغات، تاريخ، جغرافيا، علم نفس، اجتماع',
    about: 'أربع سنين، وفيها أقسام كتير جدًا بين اللغات والعلوم الإنسانية والاجتماعية.',
    genericInfo: 'تمنح الكلية ليسانس الآداب في تخصصات اللغات والعلوم الإنسانية.',
  },
  {
    slug: 'alsun',
    nameAr: 'الألسن',
    fullNameAr: 'كلية الألسن',
    icon: 'globe',
    category: 'literary',
    studyYears: 4,
    summary: 'لغات وترجمة',
    about: 'أربع سنين في لغتين وترجمة، والقبول بيكون عالي في التنسيق الأدبي.',
    genericInfo: 'تمنح الكلية ليسانس الألسن في اللغات والترجمة.',
  },
  {
    slug: 'dar-uloom',
    nameAr: 'دار العلوم',
    fullNameAr: 'كلية دار العلوم',
    icon: 'history',
    category: 'literary',
    studyYears: 4,
    summary: 'لغة عربية، شريعة، فلسفة إسلامية، تاريخ',
    about: 'أربع سنين في علوم اللغة العربية والدراسات الإسلامية.',
    genericInfo: 'تمنح الكلية ليسانس دار العلوم.',
  },
  {
    slug: 'archaeology',
    nameAr: 'الآثار',
    fullNameAr: 'كلية الآثار',
    icon: 'history',
    category: 'literary',
    studyYears: 4,
    summary: 'آثار مصرية وإسلامية، ترميم',
    about: 'أربع سنين في الآثار المصرية القديمة والإسلامية والترميم.',
    genericInfo: 'تمنح الكلية ليسانس الآثار.',
  },
  {
    slug: 'tourism',
    nameAr: 'السياحة والفنادق',
    fullNameAr: 'كلية السياحة والفنادق',
    icon: 'globe',
    category: 'literary',
    studyYears: 4,
    summary: 'دراسات سياحية، إرشاد سياحي، إدارة فنادق',
    about: 'أربع سنين في ثلاث شعب غالبًا: الدراسات السياحية، والإرشاد السياحي، والدراسات الفندقية.',
    genericInfo: 'تمنح الكلية بكالوريوس السياحة والفنادق.',
  },
  {
    slug: 'social-work',
    nameAr: 'الخدمة الاجتماعية',
    fullNameAr: 'كلية الخدمة الاجتماعية',
    icon: 'people',
    category: 'literary',
    studyYears: 4,
    summary: 'خدمة اجتماعية وتنمية مجتمع',
    about: 'أربع سنين في الخدمة الاجتماعية، والتدريب الميداني جزء من الدراسة.',
    genericInfo: 'تمنح الكلية بكالوريوس الخدمة الاجتماعية.',
  },
  {
    slug: 'edu',
    nameAr: 'التربية',
    fullNameAr: 'كلية التربية',
    icon: 'cap',
    category: 'literary',
    studyYears: 4,
    summary: 'إعداد معلمين للتخصصات المختلفة',
    about: 'أربع سنين. فيها شعب أدبية وعلمية حسب المادة اللي هتدرّسها.',
    genericInfo: 'تُعد الكلية المعلمين لمراحل التعليم المختلفة.',
  },
  {
    slug: 'spec-edu',
    nameAr: 'التربية النوعية',
    fullNameAr: 'كلية التربية النوعية',
    icon: 'cap',
    category: 'arts',
    studyYears: 4,
    summary: 'تربية فنية، موسيقية، إعلام تربوي، تكنولوجيا تعليم',
    about: 'أربع سنين لإعداد معلمين في المواد النوعية، وبعض الأقسام ليها اختبار قدرات.',
    genericInfo: 'تُعد الكلية معلمي المواد النوعية.',
  },
  {
    slug: 'kg',
    nameAr: 'الطفولة المبكرة',
    fullNameAr: 'كلية التربية للطفولة المبكرة',
    icon: 'people',
    category: 'literary',
    studyYears: 4,
    summary: 'معلمات رياض أطفال وتنمية الطفل',
    about: 'أربع سنين لإعداد معلمي رياض الأطفال. في جامعات اسمها «كلية رياض الأطفال».',
    genericInfo: 'تُعد الكلية المعلمين والمتخصصين في مرحلة الطفولة المبكرة.',
  },
  {
    slug: 'pe',
    nameAr: 'التربية الرياضية',
    fullNameAr: 'كلية التربية الرياضية',
    icon: 'people',
    category: 'literary',
    studyYears: 4,
    summary: 'تدريب، تدريس تربية رياضية، إدارة رياضية',
    about:
      'أربع سنين، والقبول باختبارات قدرات بدنية. في جامعات اسمها اتغير لـ«علوم الرياضة»، وفي كليات منفصلة للبنين والبنات.',
    genericInfo: 'تقبل الكلية الطلاب بعد اجتياز اختبارات القدرات.',
  },
  {
    slug: 'disability',
    nameAr: 'ذوي الإعاقة والتأهيل',
    fullNameAr: 'كلية علوم ذوي الإعاقة والتأهيل',
    icon: 'people',
    category: 'literary',
    studyYears: 4,
    summary: 'تأهيل وتعليم ذوي الاحتياجات الخاصة',
    about: 'أربع سنين في علوم الإعاقة والتأهيل.',
    genericInfo: 'كلية متخصصة في تأهيل ذوي الإعاقة.',
  },
  {
    slug: 'girls',
    nameAr: 'كلية البنات',
    fullNameAr: 'كلية البنات للآداب والعلوم والتربية',
    icon: 'cap',
    category: 'literary',
    studyYears: 4,
    summary: 'آداب وعلوم وتربية للطالبات',
    about: 'كلية للطالبات فيها شعب آداب وعلوم وتربية.',
    genericInfo: 'كلية للبنات تضم شعب الآداب والعلوم والتربية.',
  },

  {
    slug: 'mgmt-tech',
    nameAr: 'تكنولوجيا الإدارة ونظم المعلومات',
    fullNameAr: 'كلية تكنولوجيا الإدارة ونظم المعلومات',
    icon: 'chart',
    category: 'literary',
    studyYears: 4,
    summary: 'إدارة أعمال ونظم معلومات',
    about: 'برامج بتجمع بين الإدارة ونظم المعلومات.',
    genericInfo: 'كلية تجمع بين علوم الإدارة وتكنولوجيا المعلومات.',
  },
  {
    slug: 'tech-dev',
    nameAr: 'التكنولوجيا والتنمية',
    fullNameAr: 'كلية التكنولوجيا والتنمية',
    icon: 'globe',
    category: 'science',
    studyYears: 4,
    summary: 'برامج تطبيقية في التنمية',
    about: 'برامج تطبيقية، وتفاصيلها في صفحة الكلية في الجامعة.',
    genericInfo: 'كلية تقدم برامج تطبيقية في مجالات التنمية.',
  },

  // ---------- Al-Azhar (Azhari secondary certificate holders only) ----------
  {
    slug: 'usul-din',
    nameAr: 'أصول الدين والدعوة',
    fullNameAr: 'كلية أصول الدين والدعوة',
    icon: 'history',
    category: 'literary',
    studyYears: 4,
    summary: 'تفسير، حديث، عقيدة، دعوة',
    about: 'كلية أزهرية لطلاب الثانوية الأزهرية: علوم القرآن والحديث والعقيدة والدعوة.',
    genericInfo: 'تمنح الكلية الإجازة العالية (الليسانس) في أصول الدين.',
  },
  {
    slug: 'sharia-law',
    nameAr: 'الشريعة والقانون',
    fullNameAr: 'كلية الشريعة والقانون',
    icon: 'scale',
    category: 'literary',
    studyYears: 4,
    summary: 'فقه، أصول فقه، وقانون',
    about: 'كلية أزهرية بتجمع بين الشريعة الإسلامية والقانون الوضعي.',
    genericInfo: 'تمنح الكلية الإجازة العالية في الشريعة والقانون.',
  },
  {
    slug: 'arabic-lang',
    nameAr: 'اللغة العربية',
    fullNameAr: 'كلية اللغة العربية',
    icon: 'history',
    category: 'literary',
    studyYears: 4,
    summary: 'نحو وصرف، بلاغة، أدب ونقد، تاريخ',
    about: 'كلية أزهرية متخصصة في علوم اللغة العربية وآدابها.',
    genericInfo: 'تمنح الكلية الإجازة العالية في اللغة العربية.',
  },
  {
    slug: 'islamic-arabic',
    nameAr: 'الدراسات الإسلامية والعربية',
    fullNameAr: 'كلية الدراسات الإسلامية والعربية',
    icon: 'history',
    category: 'literary',
    studyYears: 4,
    summary: 'شريعة، أصول دين، لغة عربية',
    about:
      'كلية أزهرية فيها شعب في الشريعة وأصول الدين واللغة العربية، وفيها كليات للبنين وكليات للبنات.',
    genericInfo: 'تمنح الكلية الإجازة العالية في الدراسات الإسلامية والعربية.',
  },
  {
    slug: 'dawa',
    nameAr: 'الدعوة الإسلامية',
    fullNameAr: 'كلية الدعوة الإسلامية',
    icon: 'history',
    category: 'literary',
    studyYears: 4,
    summary: 'إعداد الدعاة',
    about: 'كلية أزهرية متخصصة في إعداد الدعاة.',
    genericInfo: 'تمنح الكلية الإجازة العالية في الدعوة الإسلامية.',
  },
  {
    slug: 'quran',
    nameAr: 'القرآن الكريم',
    fullNameAr: 'كلية القرآن الكريم للقراءات وعلومها',
    icon: 'history',
    category: 'literary',
    studyYears: 4,
    summary: 'القراءات وعلوم القرآن',
    about: 'كلية أزهرية متخصصة في القراءات وعلوم القرآن الكريم.',
    genericInfo: 'تمنح الكلية الإجازة العالية في القراءات وعلومها.',
  },
  {
    slug: 'human-studies',
    nameAr: 'الدراسات الإنسانية',
    fullNameAr: 'كلية الدراسات الإنسانية',
    icon: 'history',
    category: 'literary',
    studyYears: 4,
    summary: 'لغات، تاريخ، جغرافيا، علم نفس واجتماع',
    about: 'كلية أزهرية للبنات في العلوم الإنسانية واللغات.',
    genericInfo: 'تمنح الكلية الإجازة العالية في الدراسات الإنسانية.',
  },
  {
    slug: 'azhar-girls',
    nameAr: 'البنات الأزهرية',
    fullNameAr: 'كلية البنات الأزهرية',
    icon: 'cap',
    category: 'literary',
    studyYears: 4,
    summary: 'شعب علمية وأدبية وشرعية للطالبات',
    about: 'كليات أزهرية للطالبات في محافظات مختلفة، فيها شعب متنوعة حسب الكلية.',
    genericInfo: 'كليات للبنات تابعة لجامعة الأزهر.',
  },
  {
    slug: 'agri-eng',
    nameAr: 'الهندسة الزراعية',
    fullNameAr: 'كلية الهندسة الزراعية',
    icon: 'gear',
    category: 'engineering',
    studyYears: 4,
    summary: 'ميكنة زراعية، ري، هندسة نظم زراعية',
    about: 'كلية أزهرية في الهندسة المرتبطة بالزراعة.',
    genericInfo: 'تمنح الكلية بكالوريوس الهندسة الزراعية.',
  },

  // ---------- arts ----------
  {
    slug: 'arch',
    nameAr: 'الفنون الجميلة',
    fullNameAr: 'كلية الفنون الجميلة',
    icon: 'building',
    category: 'arts',
    studyYears: 5,
    summary: 'عمارة، ديكور، جرافيك، تصوير، نحت',
    about:
      'القبول بعد اختبار قدرات. فيها قسم عمارة للشعبة الهندسية في جامعات زي الإسكندرية وأسيوط والمنصورة وحلوان والمنيا.',
    genericInfo: 'تقبل الكلية الطلاب بعد اجتياز اختبار القدرات، وتضم أقسامًا فنية متعددة.',
  },
  {
    slug: 'applied-arts',
    nameAr: 'الفنون التطبيقية',
    fullNameAr: 'كلية الفنون التطبيقية',
    icon: 'building',
    category: 'arts',
    studyYears: 5,
    summary: 'تصميم صناعي، إعلان، طباعة، أثاث، نسيج',
    about: 'القبول بعد اختبار قدرات. الأقسام مرتبطة بالصناعة والتصميم.',
    genericInfo: 'تقبل الكلية الطلاب بعد اجتياز اختبار القدرات.',
  },
  {
    slug: 'art-edu',
    nameAr: 'التربية الفنية',
    fullNameAr: 'كلية التربية الفنية',
    icon: 'building',
    category: 'arts',
    studyYears: 4,
    summary: 'إعداد معلم تربية فنية',
    about: 'أربع سنين، والقبول باختبار قدرات.',
    genericInfo: 'تُعد الكلية معلمي التربية الفنية.',
  },
  {
    slug: 'music-edu',
    nameAr: 'التربية الموسيقية',
    fullNameAr: 'كلية التربية الموسيقية',
    icon: 'mic',
    category: 'arts',
    studyYears: 4,
    summary: 'إعداد معلم موسيقى',
    about: 'أربع سنين، والقبول باختبار قدرات موسيقية.',
    genericInfo: 'تُعد الكلية معلمي التربية الموسيقية.',
  },
];
