/**
 * Undergraduate faculties of the 28 public universities (Phase 11, real data, checked 2026-10-09).
 *
 * A faculty is listed only with evidence from at least one of: the Tansik 2026 cutoff announcement,
 * NAQAAE accreditation decisions, the university's Arabic Wikipedia article (raw text), or the
 * university's own site. Doubtful single-source entries (e.g. faculties described as planned) were
 * left out. Postgraduate-only institutes are not listed — high-school students cannot apply to them.
 *
 * `[kind, name?]` — name only when it differs from the kind's standard name.
 */
export type FacultyEntry = readonly [kind: string, nameAr?: string];

const WIKI = (title: string) => `https://ar.wikipedia.org/wiki/${encodeURIComponent(title)}`;
export const TANSIK_2026_SOURCE = 'https://www.youm7.com/story/2026/8/10/-/7509371';
export const NAQAAE_SOURCE =
  'https://naqaae.eg/ar/accredited_organization/decisions_higher_education';

export const PUBLIC_FACULTIES: Record<string, { sources: string[]; faculties: FacultyEntry[] }> = {
  cairo: {
    sources: [WIKI('جامعة القاهرة'), NAQAAE_SOURCE, TANSIK_2026_SOURCE, 'https://fcai.cu.edu.eg'],
    faculties: [
      ['med', 'كلية الطب (قصر العيني)'],
      ['dent'],
      ['pharm'],
      ['pt'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['planning'],
      ['cs', 'كلية الحاسبات والذكاء الاصطناعي'],
      ['sci'],
      ['agri'],
      ['econ-pol'],
      ['media'],
      ['law'],
      ['com'],
      ['arts'],
      ['dar-uloom'],
      ['archaeology'],
      ['spec-edu'],
      ['kg'],
    ],
  },
  alexandria: {
    sources: [WIKI('جامعة الإسكندرية'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['arch'],
      ['cs', 'كلية الحاسبات وعلوم البيانات'],
      ['sci'],
      ['agri'],
      ['agri', 'كلية الزراعة - سابا باشا'],
      ['econ-pol', 'كلية الدراسات الاقتصادية والعلوم السياسية'],
      ['com', 'كلية الأعمال'],
      ['law'],
      ['arts'],
      ['edu'],
      ['spec-edu'],
      ['kg'],
      ['tourism'],
      ['pe', 'كلية التربية الرياضية للبنين'],
      ['pe', 'كلية التربية الرياضية للبنات'],
    ],
  },
  'ain-shams': {
    sources: [WIKI('جامعة عين شمس'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['eng'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['alsun'],
      ['media'],
      ['archaeology'],
      ['law'],
      ['com'],
      ['arts'],
      ['edu'],
      ['spec-edu'],
      ['girls'],
    ],
  },
  assiut: {
    sources: [WIKI('جامعة أسيوط'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['arch'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['sugar-tech'],
      ['law'],
      ['com'],
      ['arts'],
      ['edu'],
      ['spec-edu'],
      ['kg'],
      ['social-work'],
      ['pe'],
    ],
  },
  tanta: {
    sources: [WIKI('جامعة طنطا'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['eng'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['law'],
      ['com'],
      ['arts'],
      ['edu'],
      ['spec-edu'],
      ['pe'],
    ],
  },
  mansoura: {
    sources: [WIKI('جامعة المنصورة'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['arch'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['law'],
      ['com'],
      ['arts'],
      ['edu'],
      ['spec-edu'],
      ['kg', 'كلية رياض الأطفال'],
      ['tourism'],
      ['pe'],
    ],
  },
  zagazig: {
    sources: [WIKI('جامعة الزقازيق'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med', 'كلية الطب البشري'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['tech-dev'],
      ['law'],
      ['com'],
      ['arts'],
      ['archaeology'],
      ['edu'],
      ['spec-edu'],
      ['kg'],
      ['disability'],
      ['pe', 'كلية التربية الرياضية للبنين'],
      ['pe', 'كلية التربية الرياضية للبنات'],
    ],
  },
  capital: {
    sources: [WIKI('جامعة حلوان'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['pharm'],
      ['nursing'],
      ['nutrition'],
      ['eng', 'كلية الهندسة بحلوان'],
      ['eng', 'كلية الهندسة بالمطرية'],
      ['tech-edu'],
      ['cs', 'كلية الحاسبات والذكاء الاصطناعي'],
      ['sci'],
      ['home-econ'],
      ['com', 'كلية التجارة وإدارة الأعمال'],
      ['law'],
      ['arts'],
      ['edu'],
      ['social-work'],
      ['tourism'],
      ['arch'],
      ['applied-arts'],
      ['art-edu'],
      ['music-edu'],
      ['pe', 'كلية علوم الرياضة للبنين'],
      ['pe', 'كلية علوم الرياضة للبنات'],
    ],
  },
  minia: {
    sources: [WIKI('جامعة المنيا'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['arch'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['law'],
      ['arts'],
      ['alsun'],
      ['dar-uloom'],
      ['edu'],
      ['spec-edu'],
      ['kg'],
      ['tourism'],
      ['pe'],
    ],
  },
  menoufia: {
    sources: [WIKI('جامعة المنوفية'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['vet'],
      ['applied-med'],
      ['eng', 'كلية الهندسة بشبين الكوم'],
      ['eng-electronic', 'كلية الهندسة الإلكترونية بمنوف'],
      ['cs'],
      ['cs', 'كلية الذكاء الاصطناعي'],
      ['sci'],
      ['agri'],
      ['home-econ'],
      ['law'],
      ['com'],
      ['arts'],
      ['media'],
      ['edu'],
      ['spec-edu'],
      ['pe'],
    ],
  },
  'suez-canal': {
    sources: [WIKI('جامعة قناة السويس'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['pt'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['com'],
      ['arts'],
      ['alsun'],
      ['edu'],
      ['tourism'],
      ['pe'],
    ],
  },
  qena: {
    sources: [WIKI('جامعة جنوب الوادي'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent', 'كلية طب الفم والأسنان'],
      ['pharm'],
      ['pt'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['law'],
      ['com'],
      ['arts'],
      ['archaeology'],
      ['media', 'كلية الإعلام وتكنولوجيا الاتصال'],
      ['edu'],
      ['spec-edu'],
      ['kg', 'كلية الطفولة المبكرة'],
      ['pe', 'كلية علوم الرياضة'],
    ],
  },
  'beni-suef': {
    sources: [WIKI('جامعة بني سويف'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent', 'كلية طب الفم والأسنان'],
      ['pharm'],
      ['pt'],
      ['nursing'],
      ['health-sci'],
      ['vet'],
      ['eng'],
      ['tech-edu'],
      ['cs'],
      ['sci'],
      ['earth-sci'],
      ['space-sci'],
      ['agri'],
      ['econ-pol', 'كلية الدراسات الاقتصادية والعلوم السياسية'],
      ['media'],
      ['alsun'],
      ['law'],
      ['com'],
      ['arts'],
      ['edu'],
      ['kg', 'كلية رياض الأطفال'],
      ['social-work', 'كلية الخدمة الاجتماعية التنموية'],
      ['disability', 'كلية علوم ذوي الاحتياجات الخاصة'],
      ['tourism'],
      ['applied-arts'],
      ['pe'],
    ],
  },
  fayoum: {
    sources: [WIKI('جامعة الفيوم'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['eng'],
      ['cs', 'كلية الحاسبات والذكاء الاصطناعي'],
      ['sci'],
      ['agri'],
      ['law'],
      ['arts'],
      ['alsun'],
      ['dar-uloom'],
      ['archaeology'],
      ['edu'],
      ['spec-edu'],
      ['kg'],
      ['social-work'],
      ['tourism'],
    ],
  },
  benha: {
    sources: [WIKI('جامعة بنها'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['pt'],
      ['nursing'],
      ['vet'],
      ['eng', 'كلية الهندسة ببنها'],
      ['eng', 'كلية الهندسة بشبرا'],
      ['cs', 'كلية الحاسبات والذكاء الاصطناعي'],
      ['sci'],
      ['agri', 'كلية الزراعة بمشتهر'],
      ['law'],
      ['com'],
      ['arts'],
      ['edu'],
      ['spec-edu'],
      ['applied-arts'],
      ['pe'],
    ],
  },
  kafrelsheikh: {
    sources: [WIKI('جامعة كفر الشيخ'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent', 'كلية طب الفم والأسنان'],
      ['pharm', 'كلية الصيدلة والتصنيع الدوائي'],
      ['pt'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['cs'],
      ['cs', 'كلية الذكاء الاصطناعي'],
      ['sci'],
      ['agri'],
      ['fisheries', 'كلية علوم الثروة السمكية والمصايد'],
      ['law'],
      ['com'],
      ['arts'],
      ['alsun'],
      ['edu'],
      ['spec-edu'],
      ['pe'],
    ],
  },
  sohag: {
    sources: [WIKI('جامعة سوهاج'), TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent', 'كلية طب وجراحة الفم والأسنان'],
      ['pharm'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['tech-edu'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['law'],
      ['com'],
      ['arts'],
      ['alsun'],
      ['archaeology'],
      ['edu'],
      ['spec-edu'],
      ['kg', 'كلية رياض الأطفال'],
      ['pe'],
    ],
  },
  'port-said': {
    sources: [WIKI('جامعة بورسعيد'), TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['pharm'],
      ['pt'],
      ['nursing'],
      ['eng'],
      ['mgmt-tech'],
      ['sci'],
      ['law'],
      ['com'],
      ['arts'],
      ['edu'],
      ['spec-edu'],
      ['kg', 'كلية رياض الأطفال'],
      ['pe'],
    ],
  },
  damanhour: {
    sources: [WIKI('جامعة دمنهور'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['sci'],
      ['agri'],
      ['com'],
      ['arts'],
      ['edu'],
      ['kg'],
    ],
  },
  aswan: {
    sources: [WIKI('جامعة أسوان'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['eng-energy'],
      ['sci'],
      ['agri', 'كلية الزراعة والموارد الطبيعية'],
      ['fisheries', 'كلية تكنولوجيا المصايد والأسماك'],
      ['law'],
      ['com'],
      ['arts'],
      ['alsun'],
      ['dar-uloom'],
      ['archaeology'],
      ['edu'],
      ['spec-edu'],
      ['social-work'],
      ['tourism'],
      ['pe'],
    ],
  },
  damietta: {
    sources: [WIKI('جامعة دمياط'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['nursing'],
      ['eng'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['law'],
      ['com'],
      ['arts'],
      ['archaeology'],
      ['edu'],
      ['spec-edu'],
      ['applied-arts'],
      ['pe'],
    ],
  },
  suez: {
    sources: [WIKI('جامعة السويس'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['dent'],
      ['pharm'],
      ['pt'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['eng-petroleum'],
      ['tech-edu'],
      ['cs'],
      ['sci'],
      ['fisheries'],
      ['agri'],
      ['econ-pol', 'كلية السياسة والاقتصاد'],
      ['media', 'كلية الإعلام وتكنولوجيا الاتصال'],
      ['law'],
      ['com'],
      ['arts'],
      ['edu'],
      ['pe'],
    ],
  },
  'sadat-city': {
    sources: [WIKI('جامعة مدينة السادات'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['pharm'],
      ['vet'],
      ['cs', 'كلية الحاسبات والذكاء الاصطناعي'],
      ['law'],
      ['com'],
      ['edu'],
      ['kg'],
      ['tourism'],
      ['pe'],
    ],
  },
  arish: {
    sources: [WIKI('جامعة العريش'), TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['vet'],
      ['cs'],
      ['sci'],
      ['agri', 'كلية العلوم الزراعية البيئية'],
      ['fisheries', 'كلية الاستزراع المائي والمصايد البحرية'],
      ['home-econ'],
      ['com'],
      ['arts'],
      ['edu'],
      ['pe'],
    ],
  },
  'new-valley': {
    sources: [WIKI('جامعة الوادي الجديد'), NAQAAE_SOURCE, TANSIK_2026_SOURCE],
    faculties: [
      ['med'],
      ['pharm'],
      ['nursing'],
      ['vet'],
      ['eng'],
      ['cs'],
      ['sci'],
      ['agri'],
      ['arts'],
      ['edu'],
      ['pe'],
    ],
  },
  matrouh: {
    sources: [WIKI('جامعة مطروح'), TANSIK_2026_SOURCE],
    faculties: [
      ['nursing'],
      ['vet'],
      ['cs', 'كلية الحاسبات والذكاء الاصطناعي'],
      ['earth-sci', 'كلية علوم البترول والتعدين'],
      ['agri', 'كلية الزراعة الصحراوية'],
      ['archaeology', 'كلية الآثار واللغات'],
      ['edu'],
      ['spec-edu'],
      ['kg', 'كلية رياض الأطفال'],
      ['tourism'],
      ['pe', 'كلية التربية الرياضية للبنين'],
    ],
  },
  luxor: {
    sources: [WIKI('جامعة الأقصر'), TANSIK_2026_SOURCE],
    faculties: [['med'], ['arch'], ['alsun'], ['archaeology'], ['tourism'], ['edu'], ['cs']],
  },
  hurghada: {
    sources: [WIKI('جامعة الغردقة'), TANSIK_2026_SOURCE],
    faculties: [['edu'], ['sci'], ['tourism'], ['alsun']],
  },
};
